-- =============================================================
-- SEED: Candidatos reales Colombia 2026, Preguntas, Posiciones
-- Candidatos basados en inscritos oficiales ante la Registraduria
-- =============================================================

-- ======================== CANDIDATOS ========================
INSERT INTO candidates (id, slug, name, party, color, bio, program_pdf) VALUES
('c1', 'ivan-cepeda', 'Iván Cepeda', 'Pacto Histórico', '#FFD700',
 'Senador y defensor de derechos humanos. Candidato del Pacto Histórico con el respaldo de más de 1.5 millones de votos en consulta interna. Propone continuar reformas sociales con enfoque en paz y justicia social.',
 NULL),
('c2', 'abelardo-de-la-espriella', 'Abelardo de la Espriella', 'Defensores de la Patria', '#1E3A5F',
 'Abogado penalista y figura mediática. Candidato independiente con propuestas inspiradas en modelos de Bukele y Milei. Enfocado en seguridad, anticorrupción y reactivación económica.',
 NULL),
('c3', 'paloma-valencia', 'Paloma Valencia', 'Centro Democrático / Gran Coalición', '#0047AB',
 'Exsenadora por el Centro Democrático. Ganadora de la Gran Consulta por Colombia. Su plan "Colombia Más Grande 2026" tiene 111 medidas estructurales en seguridad, economía y modernización del Estado.',
 NULL),
('c4', 'claudia-lopez', 'Claudia López', 'Con Claudia, imparables', '#8B5CF6',
 'Exalcaldesa de Bogotá y politóloga. Ganadora de la Consulta de las Soluciones. Propone lucha contra la corrupción, recuperación del sistema de salud y generación de empleo.',
 NULL),
('c5', 'sergio-fajardo', 'Sergio Fajardo', 'Dignidad y Compromiso', '#059669',
 'Exalcalde de Medellín y exgobernador de Antioquia. Matemático de formación. En su tercer intento presidencial, propone educación, transparencia y seguridad con inteligencia.',
 NULL),
('c6', 'roy-barreras', 'Roy Barreras', 'La Fuerza / Frente por la Vida', '#DC2626',
 'Médico cirujano y exsenador. Ganador de la consulta del Frente por la Vida. Propone recuperar seguridad, estabilizar el sistema de salud y reactivar la economía con vivienda y empleo.',
 NULL);

-- ======================== PREGUNTAS ========================
INSERT INTO questions (id, text, axis, context, sort_order) VALUES
('q1',
 'El Estado debería controlar los precios de los alimentos básicos de la canasta familiar.',
 'economia',
 'Colombia enfrenta una inflación acumulada que afecta los productos de primera necesidad. Algunos candidatos proponen intervención directa en precios, otros apuestan por subsidios focalizados o libre mercado.',
 1),
('q2',
 'El sistema de salud debe garantizar cobertura universal sin intermediarios privados (EPS).',
 'salud',
 'La reforma al sistema de salud ha sido un tema central en las últimas legislaturas. Las propuestas van desde eliminar las EPS hasta fortalecerlas con mayor regulación.',
 2),
('q3',
 'La educación superior pública debería ser completamente gratuita para todos los estratos.',
 'educacion',
 'Actualmente existen programas como Generación E que subsidian parcialmente. La discusión es si la gratuidad total es fiscalmente sostenible y si beneficiaría equitativamente.',
 3),
('q4',
 'Colombia necesita aumentar la presencia militar en las zonas más afectadas por el conflicto.',
 'seguridad',
 'Las zonas rurales siguen enfrentando violencia de grupos armados ilegales. Los enfoques varían entre mayor presencia militar, inversión social, o una combinación de ambos.',
 4),
('q5',
 'Se debe prohibir la minería a gran escala en páramos y reservas naturales, sin excepciones.',
 'ambiente',
 'Colombia tiene el 50% de los páramos del mundo. La tensión entre desarrollo económico y protección ambiental es un eje central del debate electoral.',
 5),
('q6',
 'El gobierno debe ampliar significativamente los programas de transferencias monetarias a familias vulnerables.',
 'politica_social',
 'Programas como Familias en Acción y Renta Ciudadana han mostrado resultados mixtos. El debate es sobre su eficiencia, cobertura y posible desincentivo al trabajo formal.',
 6),
('q7',
 'Colombia debería buscar mayor integración económica con los países latinoamericanos, incluso si eso implica distanciarse de EE.UU.',
 'politica_exterior',
 'La política exterior colombiana históricamente ha estado alineada con Estados Unidos. Algunos candidatos proponen diversificar relaciones y fortalecer bloques como la CAN o CELAC.',
 7),
('q8',
 'Es necesaria una asamblea constituyente para reformar profundamente las instituciones políticas del país.',
 'reforma_politica',
 'La Constitución de 1991 ha tenido más de 50 reformas. Algunos consideran que se necesita un cambio estructural, mientras otros prefieren reformas graduales dentro del marco actual.',
 8),
('q9',
 'El gobierno debe priorizar la creación de empleo formal a través de incentivos fiscales a las empresas.',
 'empleo',
 'La informalidad laboral en Colombia supera el 55%. Las propuestas incluyen desde incentivos tributarios hasta programas de empleo público y fortalecimiento de la economía popular.',
 9),
('q10',
 'Colombia debe invertir masivamente en inteligencia artificial y automatización, aunque esto transforme el mercado laboral.',
 'tecnologia',
 'La revolución tecnológica ofrece oportunidades pero también riesgos de desempleo. Los candidatos difieren en qué tan agresivamente adoptar estas tecnologías y cómo mitigar su impacto social.',
 10);

-- ======================== POSICIONES (60 = 6 candidatos × 10 ejes) ========================
-- NOTA: Scores tentativos basados en investigacion de propuestas publicas.
-- Los scores definitivos saldran del pipeline de ingesta con los PDFs reales.

-- ---- c1 Iván Cepeda (Pacto Histórico) ----
INSERT INTO candidate_positions (candidate_id, axis, summary, quote, program_page, stance_score) VALUES
('c1', 'economia',
 'Propone economía productiva con intervención estatal. Fortalecimiento de la banca pública, reindustrialización y soberanía alimentaria.',
 'La economía debe estar al servicio de la gente, no al revés.',
 15, 1),
('c1', 'salud',
 'Sistema público universal de salud. Eliminación progresiva de intermediarios privados. Atención primaria territorial.',
 'La salud es un derecho fundamental, no un negocio.',
 28, 1),
('c1', 'educacion',
 'Gratuidad total en educación superior pública. Aumento del presupuesto educativo y dignificación docente.',
 'Educación gratuita y de calidad como motor de igualdad.',
 35, 1),
('c1', 'seguridad',
 'Continuidad de la paz total. Diálogo con actores armados, inversión social en territorios y desmilitarización progresiva.',
 'La paz se construye con justicia social, no solo con fusiles.',
 42, 1),
('c1', 'ambiente',
 'Transición energética acelerada. Prohibición de fracking y nueva minería en páramos. Colombia potencia de biodiversidad.',
 'No más extractivismo depredador. Colombia es potencia de la vida.',
 50, 5),
('c1', 'politica_social',
 'Ampliación de transferencias, renta básica y programas de cuidado. Enfoque en comunidades históricamente excluidas.',
 'Reparación histórica y justicia social para los más vulnerables.',
 55, 5),
('c1', 'politica_exterior',
 'Integración latinoamericana profunda. Relaciones con el Sur Global. Diversificación más allá de EE.UU.',
 'Colombia debe mirar hacia América Latina y el Sur Global.',
 62, 4),
('c1', 'reforma_politica',
 'Apertura a reformas constitucionales profundas. Participación ciudadana directa y curules para víctimas.',
 'Las instituciones deben transformarse para servir al pueblo.',
 68, 5),
('c1', 'empleo',
 'Economía popular y del cuidado. Formalización con derechos, cooperativismo y empleo público en territorios.',
 'El trabajo digno es un derecho, no un privilegio.',
 73, 5),
('c1', 'tecnologia',
 'Soberanía digital y acceso universal a internet. Tecnología al servicio de lo público, no de las corporaciones.',
 'Tecnología con enfoque social y soberanía de datos.',
 80, 2),

-- ---- c2 Abelardo de la Espriella (Defensores de la Patria) ----
('c2', 'economia',
 'Reducción drástica de impuestos. Estado mínimo eficiente. Atracción de inversión extranjera y libre mercado.',
 'Menos Estado, más libertad económica para los colombianos.',
 8, 5),
('c2', 'salud',
 'Plan de emergencia de 10 billones para estabilizar el sistema en 90 días. Mantener EPS con regulación estricta.',
 'Medicamentos a domicilio y cero filas en los hospitales.',
 12, 4),
('c2', 'educacion',
 'Educación técnica y bilingüe. Incentivos al sector privado educativo. Becas por mérito.',
 'Educación para el trabajo real, no para el desempleo ilustrado.',
 15, 4),
('c2', 'seguridad',
 'Mano dura contra el crimen. Captura de cabecillas, bombardeos de precisión, erradicación con herbicidas. Fin de la paz total.',
 'En 90 días capturaremos 10 cabecillas criminales por región.',
 3, 5),
('c2', 'ambiente',
 'Fracking con supervisión científica. Minería como motor económico. Soberanía energética sobre restricciones ambientales.',
 'El fracking responsable nos dará soberanía energética.',
 18, 1),
('c2', 'politica_social',
 'Reducción progresiva de subsidios. Empleo como mejor política social. Programas condicionados a productividad.',
 'La mejor ayuda social es un empleo, no un subsidio eterno.',
 20, 1),
('c2', 'politica_exterior',
 'Alianza fuerte con EE.UU. e Israel. Línea dura con Venezuela. Cooperación antinarcóticos prioritaria.',
 'Nuestros aliados son las democracias fuertes, no las dictaduras.',
 22, 1),
('c2', 'reforma_politica',
 'Reducción del Congreso. Anticorrupción con IA y blockchain. Sin constituyente. Extinción de dominio exprés.',
 'Bloque anticorrupción liderado desde la Presidencia con IA.',
 5, 1),
('c2', 'empleo',
 'Flexibilización laboral total. Reducción de cargas al empleador. Colombia como hub de videojuegos y tech.',
 'Si es más barato contratar, habrá más empleo formal.',
 25, 1),
('c2', 'tecnologia',
 'Colombia como hub gamer y tech de Latam. Exenciones fiscales para programadores y creadores de contenido.',
 'Convertiremos a Colombia en la capital gamer de Latinoamérica.',
 27, 4),

-- ---- c3 Paloma Valencia (Centro Democrático / Gran Coalición) ----
('c3', 'economia',
 'Economía de mercado con incentivos tributarios. Reducción del gasto público improductivo. Atracción de inversión.',
 'Colombia necesita orden fiscal y confianza para la inversión.',
 20, 4),
('c3', 'salud',
 'Estabilización del sistema de salud con modelo mixto. Tecnología e IA para diagnóstico. Telemedicina rural.',
 'Salud con tecnología: IA para diagnóstico y telemedicina rural.',
 35, 3),
('c3', 'educacion',
 'Educación técnica y tecnológica. Acceso a IA desde la educación básica. Alianzas público-privadas.',
 'Formación para el trabajo real con acceso a inteligencia artificial.',
 45, 4),
('c3', 'seguridad',
 'Fortalecimiento de la Fuerza Pública. Más pie de fuerza, inteligencia y tecnología. Fin de la paz total.',
 'Seguridad es la prioridad número uno de mi gobierno.',
 10, 5),
('c3', 'ambiente',
 'Transición energética gradual sin sacrificar la economía. Protección ambiental con desarrollo sostenible.',
 'Protección ambiental sí, pero sin destruir la economía.',
 55, 2),
('c3', 'politica_social',
 'Programas sociales focalizados y con graduación. Movilidad social basada en educación y empleo.',
 'Transformación social basada en calidad educativa y empleo.',
 60, 2),
('c3', 'politica_exterior',
 'Alianza estratégica con EE.UU. y Europa. Ingreso a OCDE. Posición firme frente a Venezuela.',
 'Colombia debe estar en la mesa de las grandes decisiones.',
 70, 2),
('c3', 'reforma_politica',
 'Reformas graduales anticorrupción con IA y blockchain. Sin constituyente. Transparencia total con auditorías automatizadas.',
 'Transparencia total con sistemas digitales basados en blockchain.',
 15, 1),
('c3', 'empleo',
 'Formalización laboral con reducción de costos al empleador. Zonas francas de empleo en regiones.',
 'Reducir costos de contratación para generar más empleo formal.',
 50, 2),
('c3', 'tecnologia',
 'Colombia como referente en IA. Modernización digital del Estado. Datos abiertos y gobierno digital.',
 'Inteligencia artificial al servicio del Estado y los ciudadanos.',
 30, 5),

-- ---- c4 Claudia López (Con Claudia, imparables) ----
('c4', 'economia',
 'Economía mixta con Estado inteligente. Lucha contra la corrupción como motor de ahorro público. Emprendimiento.',
 'Cada peso que se roba la corrupción es un peso menos para la gente.',
 12, 3),
('c4', 'salud',
 'Recuperación del sistema de salud. Modelo mixto con red pública fuerte. Atención primaria.',
 'Recuperar el sistema de salud es una emergencia nacional.',
 20, 2),
('c4', 'educacion',
 'Educación como eje de movilidad social. Jornada única, alimentación escolar y acceso a educación superior.',
 'La educación es el gran igualador social de Colombia.',
 28, 2),
('c4', 'seguridad',
 'Seguridad ciudadana con inteligencia. Combate al microtráfico y la extorsión. Policía comunitaria.',
 'Seguridad inteligente: menos corrupción, más investigación.',
 8, 3),
('c4', 'ambiente',
 'Transición energética justa. Protección de páramos y fuentes hídricas. Economía circular.',
 'La transición energética debe ser justa y proteger el agua.',
 35, 4),
('c4', 'politica_social',
 'Programas sociales basados en evidencia. Inversión en primera infancia y cuidado.',
 'Política social con resultados medibles, no con clientelismo.',
 40, 3),
('c4', 'politica_exterior',
 'Multilateralismo pragmático. Relaciones diversificadas. Liderazgo climático regional.',
 'Colombia debe tener una política exterior independiente y pragmática.',
 48, 4),
('c4', 'reforma_politica',
 'Fiscalía antimafia, tribunal de aforados. Reforma sin constituyente pero profunda.',
 'Crear una fiscalía antimafia para acabar con la corrupción política.',
 5, 3),
('c4', 'empleo',
 'Emprendimiento y economía naranja. Formalización con incentivos. Empleo femenino.',
 'Más emprendimiento, más mujeres en la economía formal.',
 42, 3),
('c4', 'tecnologia',
 'Gobierno digital anticorrupción. Trámites en línea, datos abiertos, identidad digital.',
 'Tecnología para transparencia: que cada peso público sea rastreable.',
 50, 4),

-- ---- c5 Sergio Fajardo (Dignidad y Compromiso) ----
('c5', 'economia',
 'Economía basada en infraestructura y productividad regional. Corredores logísticos intermodales.',
 'Siete corredores logísticos conectarán las regiones productivas.',
 15, 3),
('c5', 'salud',
 'Puesto de mando presidencial de salud desde el día uno. Recuperación de acceso a medicamentos y servicios.',
 'En las primeras 24 horas instalaré un puesto de mando de salud.',
 8, 2),
('c5', 'educacion',
 'Educación como pilar central. Docentes como profesionales de élite. Jóvenes en el centro de la política.',
 'Un país que paga bien a sus maestros transforma su futuro.',
 20, 2),
('c5', 'seguridad',
 'Seguridad con inteligencia. Fin de la paz total. Presencia integral del Estado, no solo militar.',
 'Seguridad con inteligencia y presencia integral del Estado.',
 25, 3),
('c5', 'ambiente',
 'Colombia potencia de biodiversidad. Financiación verde internacional. Protección de ecosistemas estratégicos.',
 'Nuestra biodiversidad es nuestro mayor activo estratégico.',
 30, 4),
('c5', 'politica_social',
 'Movilidad social real basada en educación y oportunidades. Evaluaciones de impacto obligatorias.',
 'Cada programa social debe demostrar que funciona o desaparecer.',
 35, 3),
('c5', 'politica_exterior',
 'Diplomacia basada en valores democráticos. Multilateralismo activo. Cooperación internacional.',
 'Colombia debe ser referente de democracia y cooperación.',
 40, 4),
('c5', 'reforma_politica',
 'Reformas institucionales profundas sin constituyente. Transparencia y lucha anticorrupción.',
 'Reformar las instituciones con carácter, sin destruirlas.',
 10, 2),
('c5', 'empleo',
 '440 mil empleos nuevos con 4 mil proyectos públicos. Infraestructura como generadora de empleo.',
 'Crearemos 440 mil empleos con proyectos de infraestructura.',
 45, 3),
('c5', 'tecnologia',
 'Modernización estatal con tecnología. Mapa interactivo de obras. Gobierno abierto.',
 'Tecnología para acercar el Estado a los ciudadanos.',
 48, 3),

-- ---- c6 Roy Barreras (La Fuerza / Frente por la Vida) ----
('c6', 'economia',
 'Reactivación económica con vivienda e infraestructura. Un millón de viviendas. Reforma agraria con títulos.',
 'Un millón de viviendas y titulación masiva de tierras.',
 12, 3),
('c6', 'salud',
 'Reforma al sistema de salud con modelo mixto. Sostenibilidad financiera y acceso efectivo al paciente.',
 'Salud: titularización de deuda y acceso real para el paciente.',
 18, 2),
('c6', 'educacion',
 'Escuela Virtual de Colombia. Un millón de computadores con conectividad. Emprendimiento femenino.',
 'Un millón de computadores con conectividad para niñas y jóvenes.',
 25, 3),
('c6', 'seguridad',
 'Recuperar la seguridad como prioridad. Enfoque integral: fuerza pública más inversión social.',
 'Recuperar la seguridad sin perder la esperanza de la paz.',
 8, 3),
('c6', 'ambiente',
 'Energías renovables combinadas con minería regulada y sostenible. Equilibrio entre desarrollo y protección.',
 'Renovables sí, pero con minería responsable que genere empleo.',
 30, 3),
('c6', 'politica_social',
 'Centros de emprendimiento comunitario para mujeres. Vivienda para madres comunitarias y cuidadoras.',
 'Centros de emprendimiento donde las mujeres estudien y trabajen.',
 35, 4),
('c6', 'politica_exterior',
 'Remesas como motor de vivienda social. Relaciones pragmáticas. Mediación regional.',
 'Los 14 billones en remesas pueden financiar vivienda social.',
 40, 4),
('c6', 'reforma_politica',
 'Reformas graduales con diálogo. Centro político pragmático. Unir a Colombia para sanar heridas.',
 'No estamos para extremos, estamos para sanar heridas.',
 5, 3),
('c6', 'empleo',
 'Empleo masivo vía vivienda e infraestructura. Educación para el trabajo. Formalización gradual.',
 'La vivienda genera empleo, dignidad y reactivación económica.',
 45, 4),
('c6', 'tecnologia',
 'Blockchain en salud. Digitalización de trámites. Tecnología para transparencia.',
 'Blockchain para que cada peso de la salud sea rastreable.',
 48, 3);
