-- Agregar Voto en Blanco como candidato con misma probabilidad que los demas
INSERT INTO candidates (id, slug, name, party, color, bio, program_pdf) VALUES
('c0', 'voto-en-blanco', 'Voto en Blanco', 'Ningún partido', '#9CA3AF',
 'El voto en blanco es un derecho constitucional. Representa la decisión consciente de no apoyar a ningún candidato. Si gana con mayoría absoluta, se repiten las elecciones con candidatos diferentes.',
 NULL);

-- Posiciones neutrales (stance_score=3 en todo)
-- Quien responda mayoritariamente neutral tendra alta afinidad con voto en blanco
INSERT INTO candidate_positions (candidate_id, axis, summary, quote, program_page, stance_score) VALUES
('c0', 'economia',
 'Ninguna de las propuestas económicas actuales es suficiente. Colombia necesita un debate económico más serio antes de elegir.',
 'Ninguna propuesta económica actual convence.',
 NULL, 3),
('c0', 'salud',
 'El sistema de salud necesita una reforma real, pero ninguno de los candidatos presenta una solución viable y financiable.',
 'Las propuestas de salud son insuficientes.',
 NULL, 3),
('c0', 'educacion',
 'Las propuestas educativas son promesas sin sustento fiscal. Se necesita un plan educativo serio, no eslóganes de campaña.',
 'Promesas educativas sin sustento real.',
 NULL, 3),
('c0', 'seguridad',
 'Ni la mano dura ni el diálogo puro han funcionado. Se necesita un enfoque diferente que ninguno propone con seriedad.',
 'Ni mano dura ni diálogo han resuelto la violencia.',
 NULL, 3),
('c0', 'ambiente',
 'El ambientalismo de campaña no es suficiente. Colombia necesita una política ambiental que no dependa de quien gobierne.',
 'Las promesas ambientales no sobreviven el primer año de gobierno.',
 NULL, 3),
('c0', 'politica_social',
 'Los programas sociales actuales perpetúan la dependencia. Se necesita un modelo diferente que nadie está proponiendo.',
 'Los subsidios no resuelven la pobreza estructural.',
 NULL, 3),
('c0', 'politica_exterior',
 'La política exterior colombiana no debería depender del presidente de turno. Se necesita una política de Estado, no de gobierno.',
 'La política exterior no puede cambiar cada cuatro años.',
 NULL, 3),
('c0', 'reforma_politica',
 'El problema no es la Constitución sino la clase política. Ninguna reforma funciona si la ejecutan los mismos de siempre.',
 'Reformar las instituciones con los mismos políticos no funciona.',
 NULL, 3),
('c0', 'empleo',
 'Todos prometen empleo pero ninguno explica cómo financiarlo sin endeudar al país. Las cifras de campaña no cuadran.',
 'Las promesas de empleo no tienen respaldo fiscal.',
 NULL, 3),
('c0', 'tecnologia',
 'La transformación digital requiere inversión a largo plazo, no anuncios de campaña. Ninguna propuesta es realista.',
 'Las propuestas tecnológicas son marketing electoral.',
 NULL, 3);
